Umar/GitHub ci
mitodl/social-auth-mitxpro pull request #12
Opened 2020-12-10 08:23 UTC by umarmughal824

Switch from Travis to Github CI

2020-12-10 16:18 UTC, rhysyngsun requested changes

2020-12-10 16:18 UTC, rhysyngsun commented on .github/workflows/ci.yml
> +        run: pip install Poetry
Poetry is dropping py3.5 in the next version, so we should pin the version here
```suggestion
        run: pip install  -Iv Poetry== 1.1.4
```

2020-12-11 13:59 UTC, umarmughal824 commented
@rhysyngsun your feedback is addressed so that's ready for review again.

2020-12-14 14:09 UTC, rhysyngsun approved these changes

2020-12-14 17:08 UTC, merged